version: "3.3"

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - .:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
      - cache
  db:
    image: postgres
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    restart: always
  cache:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

networks:
  bot:
    driver: bridge

volumes:
  cache: